### ISSUE TITLE
请问当时比赛计算kappa系数时去掉背景类别了吗

### ISSUE THREAD

**Issue by hs0531** [huiyiygy/rssrai2019_semantic_segmentation#1]
请问当时比赛计算kappa系数时去掉背景类别了吗

**Comment by huiyiygy** [comment]
应该没有去掉，我自己在做的时候背景类也一起算

**Comment by milleniums** [comment]
你线下的kappa也是这么低？我现在训练集和验证集都是0.70+，难道我的kappa代码写错了？

**Comment by hs0531** [comment]
> 你线下的kappa也是这么低？我现在训练集和验证集都是0.70+，难道我的kappa代码写错了？

是比较低的，但是比赛冠军的kappa系数是0.68，你是用的什么方法指标这么高呀
